### ISSUE TITLE
Wrong ConditionOperator-Usage inside UnitCountCondition

### ISSUE THREAD

**Issue by User3318** [Aceto1/Sharky-Bot-Template#5]
The IsFulfilled-function inside the UnitCountCondition file has a swapped ConditionOperator.
ConditionOperator.Equal checks for >
and ConditionOperator.Greater checks for ==
Should be swapped.

**Comment by User3318** [comment]
Same error applies for WorkerCountCondition

**Comment by Aceto1** [comment]
Closed by #6
